<a href="https://colab.research.google.com/github/princyrathi/cloud_computingPCS221/blob/main/ass1_cloud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Create a large data file (20000 x 10000) for matrix operations.



In [ ]:
import numpy as np
import os

# Define dimensions
rows = 20000
cols = 10000

# Create a large random matrix
# Using a small integer range to keep file size manageable and ensure 'similarity' for later tasks.
print(f"Creating a {rows}x{cols} matrix...")
data_matrix = np.random.randint(0, 100, size=(rows, cols), dtype=np.int8) # Using int8 for memory efficiency

# Save the matrix to a binary file
file_name = 'large_data_matrix.npy'
np.save(file_name, data_matrix)

print(f"Matrix created and saved to '{file_name}'.")
print(f"File size: {os.path.getsize(file_name) / (1024**2):.2f} MB")


Creating a 20000x10000 matrix...
Matrix created and saved to 'large_data_matrix.npy'.
File size: 190.73 MB


### 2. Assign subsequent rows to matrix first row elements.



In [ ]:
import numpy as np

# Example matrix (smaller for demonstration)
example_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print("Original Example Matrix:")
print(example_matrix)

# Interpretation 1: Take the first element of subsequent rows to form a new first row
# Create a new matrix, for simplicity let's make it the same shape initially
new_matrix_interpretation_1 = np.zeros_like(example_matrix)

# Populate the first row of the new matrix with the first element of each row from the example matrix
new_matrix_interpretation_1[0, :example_matrix.shape[0]] = example_matrix[:, 0]

print("\nNew Matrix (Interpretation 1 - first element of each row forms new first row):")
print(new_matrix_interpretation_1)


selected_elements_for_first_row = []
for i in range(1, example_matrix.shape[0]): # Iterate through subsequent rows (excluding the first)
    # For this example, let's take the second element of each subsequent row
    selected_elements_for_first_row.append(example_matrix[i, 1]) # Taking element at index 1

# Create a new matrix. For simplicity, let's make it 1xN where N is the number of selected elements.
new_first_row_matrix = np.array([selected_elements_for_first_row])

print("\nNew Matrix (Interpretation 2 - second element of subsequent rows forms new matrix's first row):")
print(new_first_row_matrix)

Original Example Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

New Matrix (Interpretation 1 - first element of each row forms new first row):
[[ 1  5  9 13]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]

New Matrix (Interpretation 2 - second element of subsequent rows forms new matrix's first row):
[[ 6 10 14]]


### 3. Group similar elements into matrix.



In [ ]:
import numpy as np

# Load the large data matrix
file_name = 'large_data_matrix.npy'
data_matrix = np.load(file_name)

print(f"Loaded matrix shape: {data_matrix.shape}")

# 3a. Identify unique elements and their counts
unique_elements, counts = np.unique(data_matrix, return_counts=True)

print("\nTop 10 Unique Elements and their Counts:")
for i in range(min(10, len(unique_elements))):
    print(f"Element: {unique_elements[i]}, Count: {counts[i]}")

print(f"Total number of unique elements: {len(unique_elements)}")



def get_group_id(value, bin_size=10):
    return value // bin_size

# Vectorize the function for efficient application
get_group_id_vec = np.vectorize(get_group_id)

# Create a smaller example matrix to demonstrate the group ID concept clearly
small_example_matrix = np.array([
    [1, 15, 22],
    [8, 11, 29],
    [5, 19, 21]
])

group_id_matrix = get_group_id_vec(small_example_matrix)

print("\nSmall Example Matrix for Grouping:")
print(small_example_matrix)
print("\nGroup ID Matrix (bin size 10):")
print(group_id_matrix)



Loaded matrix shape: (20000, 10000)

Top 10 Unique Elements and their Counts:
Element: 0, Count: 1999136
Element: 1, Count: 1999541
Element: 2, Count: 2000014
Element: 3, Count: 2000345
Element: 4, Count: 1998249
Element: 5, Count: 1999974
Element: 6, Count: 2001721
Element: 7, Count: 1999742
Element: 8, Count: 2000022
Element: 9, Count: 2000922
Total number of unique elements: 100

Small Example Matrix for Grouping:
[[ 1 15 22]
 [ 8 11 29]
 [ 5 19 21]]

Group ID Matrix (bin size 10):
[[0 1 2]
 [0 1 2]
 [0 1 2]]


### 4. Add and subtract matrices in Python.



In [ ]:
import numpy as np

# Create two example matrices of the same shape
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

# Matrix Addition
matrix_sum = matrix_a + matrix_b
print("\nMatrix A + Matrix B:")
print(matrix_sum)

# Matrix Subtraction
matrix_difference = matrix_a - matrix_b
print("\nMatrix A - Matrix B:")
print(matrix_difference)



Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix A + Matrix B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix A - Matrix B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


### 5. Create an n x n square matrix, where all the sub-matrices has the sum of opposite corner elements as even.



In [ ]:
import numpy as np

def create_special_matrix(n):
    matrix = np.zeros((n, n), dtype=int)

    for r in range(n):
        for c in range(n):
            if (r + c) % 2 == 0: # 'White' squares
                matrix[r, c] = 2 # Even number
            else: # 'Black' squares
                matrix[r, c] = 1 # Odd number

    return matrix

# Example for n=4
n = 4
special_matrix = create_special_matrix(n)

print(f"Special {n}x{n} Matrix:")
print(special_matrix)

# Verification function (optional, for testing any 2x2 sub-matrix)
def verify_submatrix_corners(matrix):
    rows, cols = matrix.shape
    is_valid = True
    for r in range(rows - 1):
        for c in range(cols - 1):
            # Consider a 2x2 sub-matrix starting at (r, c)
            top_left = matrix[r, c]
            top_right = matrix[r, c + 1]
            bottom_left = matrix[r + 1, c]
            bottom_right = matrix[r + 1, c + 1]

            # Sum of opposite corners must be even
            if (top_left + bottom_right) % 2 != 0:
                print(f"Invalid parity at submatrix starting ({r},{c}): ({top_left},{bottom_right}) sum is odd")
                is_valid = False
            if (top_right + bottom_left) % 2 != 0:
                print(f"Invalid parity at submatrix starting ({r},{c}): ({top_right},{bottom_left}) sum is odd")
                is_valid = False
    return is_valid

if verify_submatrix_corners(special_matrix):
    print("\nVerification successful: All 2x2 sub-matrices have even sum of opposite corner elements.")
else:
    print("\nVerification failed.")

Special 4x4 Matrix:
[[2 1 2 1]
 [1 2 1 2]
 [2 1 2 1]
 [1 2 1 2]]

Verification successful: All 2x2 sub-matrices have even sum of opposite corner elements.


### 6. Perform row-wise element addition in tuple matrix.


In [ ]:
import numpy as np

# Create an example 'tuple matrix'
tuple_matrix = np.array([
    [(1, 2), (3, 4), (5, 6)],
    [(7, 8), (9, 10), (11, 12)],
    [(13, 14), (15, 16), (17, 18)]
], dtype=object)

# Perform row-wise tuple addition
result = []
for row in tuple_matrix:
    sum_tuple = tuple(sum(x) for x in zip(*row))
    result.append(sum_tuple)

print(result)

[(9, 12), (27, 30), (45, 48)]
